table Orders
	lineageTag: 2d123b84-607c-4ae6-becb-b4ba1418f881

	measure 'Total Sales' = sum(Orders[Sales])
		lineageTag: 66836f4a-75b0-4352-afc3-88fd64ff8637

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Profit' = sum(Orders[Profit])
		lineageTag: 0a2a09db-bfa8-4094-9565-db949dfa7dd7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 6d2bbe6e-c808-49b1-96f6-1efc0812070a
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: e11c499f-ae46-4b0d-bc86-08cf3e8a80ed
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 50087492-4005-411d-a4e8-82d591d8acc5
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: 4a3d372d-406a-4783-ba8a-e497a8833300
			defaultHierarchy: LocalDateTable_ca28f25e-0199-4b1b-936f-92d8315a72a7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: dd9db1ed-e87d-46b5-82cd-12eafab92c3e
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: e98064bf-d656-4e33-af57-41cc3377b89f
			defaultHierarchy: LocalDateTable_b7024597-f73b-4b9d-b07b-c231d9a07c75.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: 85b67e83-06fd-4669-8918-6ac33879022c
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: aa29b43e-36aa-4c4f-9cc6-c9f3fe1b9698
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 267fe806-c7ce-4bb5-9269-174572a14fb3
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 48aaef02-5ff3-4f91-a776-c6bc0559589c
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 40f30f9d-bda2-44a4-bafc-e118679202a2
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 307bfa6d-bd6a-4f81-8407-d3f399d62c6e
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: 9190c915-38bb-47f6-bf3c-c7e38ba497ae
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: ddd38001-eae7-4905-9bf9-a4986124d1b0
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: f17230ba-83cc-42e6-bd30-5ae501e36d7f
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: b0eb7ca0-b25f-4547-9354-12ae05c76ee1
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 630c43e9-3217-490c-898f-3165dee1d946
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 45eb6e7e-978e-4ccc-965c-da7d841d898e
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: a4577cc2-f8ed-4c6d-8bec-01a95e26875f
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 4263384f-67a7-40e4-8537-184b06ccbfbe
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 9e74f311-90ba-4a8e-93c0-3cdc54d59606
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 9de55248-4935-4fa2-8a9c-6d7a07359f69
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: c699b457-85d8-4b02-8cba-c09f01ad6a1b
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Docker\Downloads\sample_superstore.xls"), null, true),
				    Orders1 = Source{[Name="Orders"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Orders1, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

